# Generated by Django 6.0.8 on 2026-08-13 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goldannouncementread',
            options={'verbose_name': 'خواندن اطلاعیه', 'verbose_name_plural': 'خواندن اطلاعیه\u200cها'},
        ),
        migrations.AddField(
            model_name='goldannouncement',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس تصویر'),
        ),
        migrations.AddField(
            model_name='goldannouncement',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='ارسال شده'),
        ),
        migrations.AddField(
            model_name='goldannouncement',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AddField(
            model_name='goldannouncement',
            name='sent_count',
            field=models.IntegerField(default=0, verbose_name='تعداد ارسال شده'),
        ),
        migrations.AddField(
            model_name='goldannouncement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='goldannouncementread',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by_users', to='admin_panel.goldannouncement'),
        ),
        migrations.AlterField(
            model_name='goldannouncementread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
