# Generated by Django 6.0.8 on 2026-08-13 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='آدرس تصویر')),
                ('target_url', models.URLField(blank=True, null=True, verbose_name='آدرس هدف')),
                ('topic', models.CharField(blank=True, help_text='مثلاً: all_users, gold_updates, etc.', max_length=100, null=True, verbose_name='تاپیک هدف')),
                ('priority', models.CharField(choices=[('high', 'بالا'), ('normal', 'معمولی'), ('low', 'پایین')], default='high', max_length=10, verbose_name='اولویت')),
                ('sent_count', models.IntegerField(default=0, verbose_name='تعداد ارسال شده')),
                ('delivered_count', models.IntegerField(default=0, verbose_name='تعداد تحویل شده')),
                ('failed_count', models.IntegerField(default=0, verbose_name='تعداد ناموفق')),
                ('is_sent', models.BooleanField(default=False, verbose_name='ارسال شده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('unread_count', models.IntegerField(default=0, verbose_name='تعداد خوانده نشده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_users', models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربران هدف')),
            ],
            options={
                'verbose_name': 'نوتیفیکیشن FCM',
                'verbose_name_plural': 'نوتیفیکیشن\u200cهای FCM',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='توکن FCM')),
                ('device_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام دستگاه')),
                ('device_type', models.CharField(choices=[('android', 'اندروید'), ('ios', 'آی\u200cاواس'), ('web', 'وب')], default='android', max_length=20, verbose_name='نوع دستگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='آخرین استفاده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'توکن FCM',
                'verbose_name_plural': 'توکن\u200cهای FCM',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'token')},
            },
        ),
        migrations.CreateModel(
            name='UserNotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خواندن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by_users', to='accounts.fcmnotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'خواندن نوتیفیکیشن',
                'verbose_name_plural': 'خواندن نوتیفیکیشن\u200cها',
                'unique_together': {('user', 'notification')},
            },
        ),
    ]
