# Generated by Django 6.0.8 on 2026-08-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fcmnotification_fcmtoken_usernotificationread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcmtoken',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='device_type',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='fcmtoken',
            table='fcm_tokens',
        ),
        migrations.RemoveField(
            model_name='fcmtoken',
            name='last_used',
        ),
    ]
